---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: jiphex/sheffe:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  ports:
    - port: 4000
      targetPort: 3333
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 4000
            path: /
      host: sheffield.xyzzy.uk
---
# permissions to do edit databases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbedit
rules:
  - apiGroups:
      - sheffield.dafni.ac.uk
    resources:
      - databases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sheffield.dafni.ac.uk
    resources:
      - databases/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: fe-db
  namespace: shef
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dbedit
subjects:
  - kind: ServiceAccount
    name: frontend
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: fe-db
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dbedit
subjects:
  - kind: ServiceAccount
    name: frontend
    namespace: default
